force-app/main/default/objects/Execution_Log__c/Execution_Log__c.object-meta.xml
<CustomObject>
    <label>Execution Log</label>
    <nameField>
        <label>Execution Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Execution_Log__c/fields/CPU_Used__c.field-meta.xml
<CustomField>
    <fullName>CPU_Used__c</fullName>
    <label>CPU Used</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Execution_Log__c/fields/DML_Count__c.field-meta.xml
<CustomField>
    <fullName>DML_Count__c</fullName>
    <label>DML Count</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Execution_Log__c/fields/Execution_Time__c.field-meta.xml
<CustomField>
    <fullName>Execution_Time__c</fullName>
    <label>Execution Time</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Execution_Log__c/fields/SOQL_Count__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Count__c</fullName>
    <label>SOQL Count</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Execution_Log__c/fields/Trigger_Name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name__c</fullName>
    <label>Trigger Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogService.cls
public with sharing class LogService {
  public static void persist(
    String className,
    Long executionTime,
    Map<String, Integer> limits,
    String errorMessage
  ) {
    /*Execution_Log__c log = new Execution_Log__c();
    log.Trigger_Name__c = className;
    log.Execution_Time__c = executionTime;
    log.CPU_Used__c = limits.get('CPU');
    log.SOQL_Count__c = limits.get('SOQL');
    log.DML_Count__c = limits.get('DML');
    log.Error_Message__c = errorMessage;

    insert log;*/
  }
}